clientrelations/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views

app_name = 'clientrelations'

urlpatterns = [
    path('general_tools', views.general_tools, name='general_tools'),
    path('other_tools', views.other_tools, name='other_tools'),
    path('aclient_tools', views.aclient_tools, name='aclient_tools'),

    path('tool_output', views.tool_output, name='tool_output'),

    path('aclient_call_log', views.aclient_call_log, name='aclient_call_log'),
    path('aclient_file_merger', views.aclient_file_merger, name='aclient_file_merger'),

    path('sectional_call_logs', views.sectional_call_logs, name='sectional_call_logs'),
    path('revo_weekly_invoice', views.revo_weekly_invoice, name='revo_weekly_invoice'),
    path('', RedirectView.as_view(url=reverse_lazy('other_tools'), permanent=True)),

    path('email_retrieval', views.email_retrieval, name='email_retrieval'),
    path('email_retrieval/search', views.email_search, name='email_search'),
    path('email_retrieval/search_status/<str:taskId>/', views.email_search_status, name='email_search_status'),
    path('email_retrieval/html/<str:emailID>/', views.email_retrieval_html, name='email_retrieval_html'),
    path('email_retrieval/eml/<str:emailID>/', views.email_retrieval_eml, name='email_retrieval_eml'),

    path('email_retrieval/bulk/', views.email_bulk_retrieval, name='email_bulk_retrieval'),
    path('email_retrieval/start_email_zip_task/', views.start_email_zip_task, name='start_email_zip'),
    path('email_retrieval/email_zip_status/<str:taskId>/', views.check_zip_task_status, name='email_zip_status'),
]

mab/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('add_tool/<str:link_name>', views.add_tool_to_dashboard, name='add_tool_to_dashboard'),
    path('remove_tool/<str:link_name>', views.remove_tool_from_dashboard, name='remove_tool_from_dashboard'),
    path('admin', admin.site.urls),
    path('clientrelations/', include('clientrelations.urls', namespace='clientrelations')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('riskmanagement/', include('riskmanagement.urls', namespace='riskmanagement')),
    path('', RedirectView.as_view(url=reverse_lazy('login'), permanent=True)),
]

clientrelations/models.py
from django.db import models

class ClientRelationsPermissions(models.Model):
    """
    Dummy model for defining custom permission related to Client Relations.
    """

    class Meta:
        managed = False  # don't create the model in the database
        permissions = [
            ("access_client_relations", "Can access the Client Relations section"),
        ]
        

clientrelations/views.py
import os
import json
import requests
import zipfile
import pandas as pd
from datetime import datetime, timedelta
from urllib.parse import urlencode
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core import serializers
from django.core.cache import cache
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.generator import BytesGenerator
from io import BytesIO
from mab.utils.file_utils import retreive_header_and_footer
from mab.utils.email_utils import send_email_with_attachment
from mab.utils.archiving_utils import safe_move
from mab.utils.clientrelations_excel_report_utils import create_bank_sif_report, create_revo_weekly_invoices, create_aclient_call_logs, create_sectional_call_logs
from mab.tasks import fetch_letter_data, build_email_zip_for_client
from celery.result import AsyncResult

# Views that just display pages
@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def general_tools(request):
    return render(request, 'clientrelations/general_tools.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def other_tools(request):
    return render(request, 'clientrelations/other_tools.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def aclient_tools(request):
    return render(request, 'clientrelations/aclient_tools.html')


# View used to output information after a client relations tools has been used
@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def tool_output(request):
    return render(request, 'clientrelations/tool_output.html')


# Views with unique functions #######################################################################
@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def email_retrieval(request):
    return render(request, 'clientrelations/cr_tool_templates/email_retrieval.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def email_search(request):
    if request.method == "POST":
        letter_search_post_data = json.loads(request.body)
        # Trigger celery task
        task = fetch_letter_data.delay(letter_search_post_data)
        # Return the task id so the front-end can poll for results
        return JsonResponse({'task_id': task.id}, safe=False)
    

@login_required
def email_search_status(request, taskId):
    result = AsyncResult(taskId)
    if result.ready():
        # When task is complete, return the result
        return JsonResponse(result.result, safe=False)
    else:
        return JsonResponse({'status': 'PENDING'})


def email_retrieval_html(request, emailID):
    api_url = f'http://host.docker.internal:3000/api/letters?ReceivedEmailID={emailID}'

    try:
        response = requests.get(api_url, headers={ 'x-api-key': os.getenv('API_KEY') })
        response.raise_for_status()

        letter_data = response.json()['results']

    except requests.exceptions.RequestException as e:
        print(e)
        pass
        # TODO: THIS PROBABLY WON"T WORK HERE
        #messages.error(request, f"An error occured using the KPI API: {str(e)}.")


    return HttpResponse(letter_data[0]['HTML'])


def email_retrieval_eml(request, emailID):
    api_url = f'http://host.docker.internal:3000/api/letters?ReceivedEmailID={emailID}'

    try:
        response = requests.get(api_url, headers={ 'x-api-key': os.getenv('API_KEY') })
        response.raise_for_status()

        letter_data = response.json()['results']

    except requests.exceptions.RequestException as e:
        print(e)
        pass
        # TODO: THIS PROBABLY WON"T WORK HERE
        #messages.error(request, f"An error occured using the KPI API: {str(e)}.")

    email_datetime_obj = datetime.strptime(letter_data[0]['EmailDate'], "%Y-%m-%dT%H:%M:%S.000Z")
    formated_email_date = email_datetime_obj.strftime("%a, %d %b %Y %H:%M:%S +0000")

    email = MIMEMultipart()
    email['Subject'] = letter_data[0]['EmailSubject']
    email['From'] = letter_data[0]['EmailFrom']
    email['To'] = letter_data[0]['EmailTo']
    email['Date'] = formated_email_date

    body = letter_data[0]['HTML']
    email.attach(MIMEText(body, "html"))

    email_content = email.as_string()

    response = HttpResponse(
        email_content,
        content_type="message/rfc822",
    )
    filename = letter_data[0]['ReferenceNumber']
    response["Content-Disposition"] = f"attachment; filename={filename}.eml"
    return response


# Email Bulk Download Views
@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def email_bulk_retrieval(request):
    return render(request, 'clientrelations/cr_tool_templates/email_zip_retrieval.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def start_email_zip_task(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=400)
    
    data = json.loads(request.body)
    client = data.get('client')
    date = data.get('email_date')

    if not client or not date:
        return JsonResponse({'error': 'Missing client or date'}, status=400)
    
    task = build_email_zip_for_client.delay(client, date)
    return JsonResponse({'task_id': task.id})


@login_required
def check_zip_task_status(request, taskId):
    result = AsyncResult(taskId)

    if result.ready():
        if result.successful():
            return JsonResponse(result.result)
        else:
            return JsonResponse({'status': 'error', 'message': 'Task Failed'}, status=500)
    else:
        return JsonResponse({'status': 'pending'})
    

@login_required
def download_email_zip(request, token):
    zip_data = cache.get(f"email_zip_{token}")
    if not zip_data:
        return HttpResponse('File expired or invalid.', status=404)
    
    response = HttpResponse(zip_data, content_type="application/zip")
    response['Content-Disposition'] = f"attachment; filename={token}.zip"
    return response


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def aclient_call_log(request):
    if request.method == 'POST' and 'button_pressed' in request.POST:
        ACLIENT_MONTHLY_CALL_LOG_DIRECTORY = '/mnt/newbiz/AClient/call_report/'
        ACLIENT_QUARTERLY_CALL_LOG_DIRECTORY = '/mnt/newbiz/AClient/call_report/'

        report_period = request.POST.get('period')

        if report_period == "Monthly":
            create_aclient_call_logs("Monthly", ACLIENT_MONTHLY_CALL_LOG_DIRECTORY, )
            messages.success(request, f'AClient Monthly Call Log created in {ACLIENT_MONTHLY_CALL_LOG_DIRECTORY}')
        elif report_period == "Quarterly":
            create_aclient_call_logs("Quarterly", ACLIENT_QUARTERLY_CALL_LOG_DIRECTORY, )
            messages.success(request, f'AClient Quarterly Call Log created in {ACLIENT_QUARTERLY_CALL_LOG_DIRECTORY}')
        else:
            messages.error(request, f'Selected AClient call log period was not an option.')

        return render(request, 'clientrelations/cr_tool_templates/tool_output.html')

    return render(request, 'clientrelations/cr_tool_templates/aclient_call_log.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def aclient_file_merger(request):
    if request.method == 'POST' and 'button_pressed' in request.POST:
        ACLIENT_FILE_MERGE_DIRECTORY = '/mnt/newbiz/AClient/remit/'

        data =[]
        for file in os.listdir(ACLIENT_FILE_MERGE_DIRECTORY):
            if file.endswith(".txt") and file.startswith("AClient"):
                aclient_file_merge_dataframe = pd.read_csv(os.path.join(ACLIENT_FILE_MERGE_DIRECTORY, file), header=None)
                data.append(aclient_file_merge_dataframe)

        combined_aclient_dataframes = pd.concat(data, ignore_index=True)

        output_filename = os.path.join(ACLIENT_FILE_MERGE_DIRECTORY, 'output.xlsx')
        combined_aclient_dataframes.to_excel(output_filename, index=False, header=False)

        messages.success(request, f'Files in {ACLIENT_FILE_MERGE_DIRECTORY} have been successfully merged.')

        return render(request, 'clientrelations/cr_tool_templates/tool_output.html')

    return render(request, 'clientrelations/cr_tool_templates/aclient_file_merger.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def revo_weekly_invoice(request):
    if request.method == 'POST' and 'button_pressed' in request.POST:
        revo_weekly_invoice_DIRECTORY = '/mnt/newbiz/Revo/remit/Weekly remit recap'

        create_revo_weekly_invoices(revo_weekly_invoice_DIRECTORY)

        messages.success(request, f'Revo weekly invoices created in {revo_weekly_invoice_DIRECTORY}')

        return render(request, 'clientrelations/cr_tool_templates/tool_output.html')

    return render(request, 'clientrelations/cr_tool_templates/revo_weekly_invoice.html')


@login_required
@permission_required('clientrelations.access_client_relations', raise_exception=True)
def sectional_call_logs(request):
    if request.method == 'POST' and 'button_pressed' in request.POST:
        sectional_call_logs_DIRECTORY = '/mnt/newbiz/Sectional/call_report'

        create_sectional_call_logs(sectional_call_logs_DIRECTORY)

        messages.success(request, f'Sectional Call Log successfully created in {sectional_call_logs_DIRECTORY}')

        return render(request, 'clientrelations/cr_tool_templates/tool_output.html')

    return render(request, 'clientrelations/cr_tool_templates/sectional_call_logs.html')

clientrelations/templates/clientrelations/cr_tool_templates/aclient_call_log.html
{% extends 'clientrelations/cr_base_templates/cr_tool_base.html' %}
{% load bootstrap4 %} 

{% block tool_content %}

<div class="row">
    <div class="col-12 text-center">
        <h1 class="mx-auto">AClient Call Log</h1>
    </div>
</div>
<p>Create the AClient Monthly and Quarterly call logs by searching the \\nas4\client\newbiz\AClient\call_report\
    folder for files that start with "AClient_call_" and retriveing the data from them.
</p>

<div class="row">
    <div class="col-12 text-center mt-3">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="period">Choose Report Period:
                <select class="form-control" id="period" name="period">
                    <option value="Monthly">Monthly</option>
                    <option value="Quarterly">Quarterly</option>
                </select></label>
            </div>
            <br>
            <input type="hidden" name="button_pressed" value="true">
            <button type="submit" class="btn btn-primary">Create Call Log</button>
        </form>
    </div>
</div>

{% endblock tool_content %}

{% block add_remove_button %}
    {% include 'mab/tool_add_remove_buttons.html' with link_name='AClient Call Log' %}
{% endblock add_remove_button %}

clientrelations/templates/clientrelations/cr_tool_templates/aclient_file_merger.html
{% extends 'clientrelations/cr_base_templates/cr_tool_base.html' %}
{% load bootstrap4 %} 

{% block tool_content %}

<div class="row">
    <div class="col-12 text-center">
        <h1 class="mx-auto">AClient File Merger</h1>
    </div>
</div>
<p>Search the \\nas4\client\newbiz\AClient\remit\ folder for text files that start with "ACL" and merge them into a single excel file.</p>

<div class="row">
    <div class="col-12 text-center mt-3">
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="button_pressed" value="true">
            <button type="submit" class="btn btn-primary">Merge Files</button>
        </form>
    </div>
</div>

{% endblock tool_content %}

{% block add_remove_button %}
    {% include 'mab/tool_add_remove_buttons.html' with link_name='AClient File Merger' %}
{% endblock add_remove_button %}

clientrelations/templates/clientrelations/cr_tool_templates/email_retrieval.html
{% extends 'operations/op_base_templates/op_report_base.html' %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block report_content %}
<div class="container pb-1">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="mx-auto">Email Search</h1>
        </div>
    </div>

    <div id="app">
        <form method="POST" class="form-inline" @submit.prevent="submitForm()">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <label class="me-2" for='refnum'>Reference #</label>
                    <input type="text" class="form-control" id="refnum" name="refnum" v-model="refnum" maxlength="8" autocomplete="off">
                </div>
                <div class="col">
                    <label class="me-2" for='client'>Client</label>
                    <select class="form-control" id="client" name="client" v-model="client">
                        <option value="" selected>All Clients</option>
                        <option value="ABank">ABank</option>
                        <option value="EnergyComp">EnergyComp</option>
                        <option value="InsuranceComp">InsuranceComp</option>
                        <option value="MoreEnergy">MoreEnergy</option>
                        <option value="PARKS">PARKS</option>
                        <option value="Chips">Chips (SpotLoan)</option>
                        <option value="ALF">ALF/Finwise/LTO</option>
                        <option value="PURE">PURE</option>
                    </select>
                </div>
            </div>
    
            <div class="row">
                <div class="col">
                    <label class="me-2" for="startDate">Start Date</label>
                    <input type="date" class="form-control" id="startDate" name="startDate" v-model="startDate">
                </div>
                <div class="col">
                    <label class="me-2" for="endDate">End Date</label>
                    <input type="date" class="form-control" id="endDate" name="endDate" v-model="endDate">
                </div>
            </div>
    
            <label class="me-2" for='recieverName'>Name</label>
            <input type="text" class="form-control" id="recieverName" name="recieverName" v-model="recieverName" maxlength="50" autocomplete="off">
            
            <div class="container mt-5 mb-2">
                <button class="btn btn-primary mt-2" type="submit">Submit</button>
                <a class="btn btn-secondary me-2" href="{% url 'clientrelations:email_bulk_retrieval' %}" style="float:right">Bulk Retrieval</a>
            </div>
        </form>

        <div v-if="loading" class="pb-3">
            <h3 class="text-center">Loading...</h3>
        </div>

        <div v-if="data">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>View</th>
                            <th>Reference #</th>
                            <th>Email Date</th>
                            <th>Recipient</th>
                            <th>Subject</th>
                            <th>Client</th>
                        </tr>
                    </thead>
                    <tbody>                    
                        <tr v-for="(letter, index) in data" :key="index">
                            <td>
                                <a :href="`${baseUrlHTML}${letter.ReceivedEmailID}`" class="btn btn-light" target="_blank">
                                    <span class="material-icons">pageview</span>
                                </a>
                                <a :href="`${baseUrlEml}${letter.ReceivedEmailID}`" class="btn btn-light" target="_blank">
                                    <span class="material-symbols-outlined">mail</span>
                                </a>
                            </td>
                            <td>[[ letter.ReferenceNumber ]]</td>
                            <td class="text-nowrap">[[ formatDate(letter.EmailDate) ]]</td>
                            <td>[[ letter.EmailTo ]]</td>
                            <td>[[ letter.EmailSubject ]]</td>
                            <td>[[ letter.EmailBcc ]]</td>
                        </tr>
                        
                    </tbody>
                </table>
            </div>

            <ul class="pagination justify-content-center">
                <li :class="['page-item', { disabled: currentPage === 1 }]" @click="currentPage > 1 && changePage(currentPage - 1)">
                    <a class="page-link">Previous</a>
                </li>

                <li v-for="page in visiblePages" :key="page" :class="['page-item', { active: page === currentPage }]" @click="page !== currentPage && changePage(page)">
                    <a class="page-link">[[ page ]]</a>
                </li>

                <li :class="['page-item', { disabled: currentPage === totalPages }]" @click="currentPage < totalPages && changePage(currentPage + 1)">
                    <a class="page-link">Next</a>
                </li>
            </ul>
        </div>
    </div>

</div>
{% endblock report_content %}

{% block add_remove_button %}
    {% include 'mab/tool_add_remove_buttons.html' with link_name='Email Search' %}
{% endblock add_remove_button %}

{% block scripts %}
{% comment %} <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script> {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.7.16"></script>

<script>
    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            loading: false,
            baseUrlHTML: "/clientrelations/email_retrieval/html/",
            baseUrlEml: "/clientrelations/email_retrieval/eml/",
            refnum: null,
            client: null,
            startDate: null,
            endDate: null,
            recieverName: null,
            data: null,
            currentPage: 1,
            itemsPerPage: 25,
            totalItems: 0,
            maxVisiblePages: 21,
        },
        computed: {
            totalPages() {
                return Math.ceil(this.totalItems / this.itemsPerPage)
            },
            visiblePages() {
                const half = Math.floor(this.maxVisiblePages / 2);
                let start = Math.max(1, this.currentPage - half);
                let end = Math.min(this.totalPages, this.currentPage + half);

                // Adjust if we're near the start or end
                if (this.currentPage <= half) {
                    end = Math.min(this.totalPages, start + this.maxVisiblePages - 1);
                } else if (this.currentPage + half >= this.totalPages) {
                    start = Math.max(1, this.totalPages - this.maxVisiblePages + 1)
                }

                return Array.from({ length: end - start + 1 }, (_, i) => i + start);
            },
        },
        methods: {
            formatDate(value) {
                const date = new Date(value);
                return date.toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: '2-digit',
                    day: '2-digit',
                });
            },
            submitForm() {
                this.currentPage = 1;
                this.submitLetterQuery();
            },
            changePage(page) {
                this.currentPage = page;
                this.submitLetterQuery();
            },
            submitLetterQuery() {
                if (this.recieverName && (!this.startDate || !this.endDate)) {
                    alert("Please provide both Start Date and End Date when suing the Name field.");
                    this.loading = false;
                    return;
                }

                // Reset state
                this.totalItems = 0;
                this.data = null;
                this.loading = true;

                fetch('{% url 'clientrelations:email_search' %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    body: JSON.stringify({ 
                        refnum: this.refnum,
                        client: this.client,
                        startDate: this.startDate,
                        endDate: this.endDate,
                        recieverName: this.recieverName,
                        page: this.currentPage,
                        limit: this.itemsPerPage
                     }),
                })
                .then(response => response.json())
                .then(json => {
                    const taskId = json.task_id
                    this.pollTask(taskId)
                })
                .catch(error => {
                    console.error('Error: ', error);
                    this.loading = false;
                });
                
            },

            pollTask(taskId) {
                // Poll the status endpoint every few seconds
                const pollInterval = setInterval(() => {
                    fetch(`/clientrelations/email_retrieval/search_status/${taskId}/`)
                    .then(response => response.json())
                    .then(json => {
                        if (json.status !== 'PENDING') {
                            this.data = json.results;
                            this.totalItems = json.total;
                            this.loading = false;
                            clearInterval(pollInterval);
                        }
                    })
                    .catch(error => {
                        console.error("Polling error:", error);
                        clearInterval(pollInterval);
                        this.loading = false;
                    });
                }, 3000);  // poll every 3 seconds
            }
        }
    });
</script>

{% endblock scripts %}

clientrelations/templates/clientrelations/cr_tool_templates/email_zip_retrieval.html
{% extends 'operations/op_base_templates/op_report_base.html' %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block report_content %}
<div class="container pb-1">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="mx-auto">Email Bulk Retrieval</h1>
        </div>
    </div>

    <div id="app">
        <form method="POST" class="form-inline" @submit.prevent="submitForm">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <label class="me-2" for='client'>Client</label>
                    <select class="form-control" id="client" name="client" v-model="client">
                        <option value="ABank" selected>ABank</option>
                        <option value="EnergyComp">EnergyComp</option>
                        <option value="InsuranceComp">InsuranceComp</option>
                        <option value="MoreEnergy">MoreEnergy</option>
                        <option value="PARKS">PARKS</option>
                        <option value="Chips">Chips (SpotLoan)</option>
                        <option value="ALF">ALF/Finwise/LTO</option>
                        <option value="PURE">PURE</option>
                    </select>
                </div>

                <div class="col">
                    <label class="me-2" for="emailDate">Date</label>
                    <input type="date" class="form-control" id="emailDate" name="emailDate" v-model="emailDate">
                </div>
            </div>
            
            <div class="container mt-5 mb-2">
                <button class="btn btn-primary mt-2" type="submit">Submit</button>
                <a class="btn btn-secondary me-2" href="{% url 'clientrelations:email_retrieval' %}" style="float:right">Back</a>
            </div>
        </form>

        <p v-if="statusMessage" class="pb-2">
            [[ statusMessage ]]
        </p>

        <a v-if="downloadUrl" :href="downloadUrl" download="emails.zip" class="btn btn-primary mb-2">
            Download Zip File
        </a>
    </div>

</div>
{% endblock report_content %}

{% block add_remove_button %}
    {% include 'mab/tool_add_remove_buttons.html' with link_name='Email Search' %}
{% endblock add_remove_button %}

{% block scripts %}
{% comment %} <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script> {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.7.16"></script>

<script>
    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            client: '',
            emailDate: '',
            statusMessage: '',
            taskId: '',
            downloadUrl: '',
            loading: false,
            pollInterval: null,
        },
        methods: {
            async submitForm() {
                this.loading = true;
                this.statusMessage = 'Submitting request...';
                this.downloadUrl = '';
                try {
                    const response = await fetch('{% url 'clientrelations:start_email_zip' %}', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}',
                        },
                        body: JSON.stringify({ 
                            client: this.client,
                            email_date: this.emailDate,
                         }),
                    })
                    const data = await response.json();
                    this.taskId = data.task_id;
                    this.statusMessage = "Processing request...";

                    this.pollInterval = setInterval(this.pollStatus, 2000);
                } catch (error) {
                    console.error('Error submitting form:', error);
                    this.statusMessage = 'Submission failed.';
                }
            },
            async pollStatus() {
                try {
                    const res = await fetch(`/clientrelations/email_retrieval/email_zip_status/${this.taskId}/`);
                    const data = await res.json();

                    if (data.status === 'pending') return;

                    clearInterval(this.pollInterval);

                    if (data.status === 'complete') {
                        const blob = this.base64ToBlob(data.zip_data, 'application/zip');
                        this.downloadUrl = URL.createObjectURL(blob)
                        this.statusMessage = 'Emails ready for download:';

                    } else {
                        this.statusMessage = data.message || 'An error occurred retrieving the emails.';
                    }

                    this.loading = false;

                } catch (error) {
                    clearInterval(this.pollInterval);
                    this.statusMessage = 'Error polling task status.';
                    this.loading = false;
                }
            },
            base64ToBlob(base64, mime) {
                const byteChars = atob(base64);
                const byteArrays = [];
                for (let offset = 0; offset < byteChars.length; offset += 512) {
                    const slice = byteChars.slice(offset, offset + 512);
                    const byteNumbers = new Array(slice.length);
                    for (let i = 0; i < slice.length; i++) {
                        byteNumbers[i] = slice.charCodeAt(i);
                    }
                    byteArrays.push(new Uint8Array(byteNumbers));
                }
                return new Blob(byteArrays, { type: mime });
            },
        }
    });
</script>

{% endblock scripts %}