clientrelations/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views

app_name = 'clientrelations'

urlpatterns = [
    path('general_tools', views.general_tools, name='general_tools'),
    path('other_tools', views.other_tools, name='other_tools'),
    path('aclient_tools', views.aclient_tools, name='aclient_tools'),

    path('tool_output', views.tool_output, name='tool_output'),

    path('aclient_call_log', views.aclient_call_log, name='aclient_call_log'),
    path('aclient_file_merger', views.aclient_file_merger, name='aclient_file_merger'),

    path('sectional_call_logs', views.sectional_call_logs, name='sectional_call_logs'),
    path('revo_weekly_invoice', views.revo_weekly_invoice, name='revo_weekly_invoice'),
    path('', RedirectView.as_view(url=reverse_lazy('other_tools'), permanent=True)),

    path('email_retrieval', views.email_retrieval, name='email_retrieval'),
    path('email_retrieval/search', views.email_search, name='email_search'),
    path('email_retrieval/search_status/<str:taskId>/', views.email_search_status, name='email_search_status'),
    path('email_retrieval/html/<str:emailID>/', views.email_retrieval_html, name='email_retrieval_html'),
    path('email_retrieval/eml/<str:emailID>/', views.email_retrieval_eml, name='email_retrieval_eml'),

    path('email_retrieval/bulk/', views.email_bulk_retrieval, name='email_bulk_retrieval'),
    path('email_retrieval/start_email_zip_task/', views.start_email_zip_task, name='start_email_zip'),
    path('email_retrieval/email_zip_status/<str:taskId>/', views.check_zip_task_status, name='email_zip_status'),
]

mab/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('add_tool/<str:link_name>', views.add_tool_to_dashboard, name='add_tool_to_dashboard'),
    path('remove_tool/<str:link_name>', views.remove_tool_from_dashboard, name='remove_tool_from_dashboard'),
    path('admin', admin.site.urls),
    path('clientrelations/', include('clientrelations.urls', namespace='clientrelations')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('riskmanagement/', include('riskmanagement.urls', namespace='riskmanagement')),
    path('', RedirectView.as_view(url=reverse_lazy('login'), permanent=True)),
]

operations/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'operations'

urlpatterns = [
    path('reports', views.reports, name='reports'),

    path('reports/agent_productivity', views.agent_productivity, name='agent_productivity'),
    path('reports/agent_productivity/get_table_data', views.agent_productivity_get_table_data, name='agent_productivity_get_table_data'),
    path('reports/agent_productivity/create_excel_file', views.agent_productivity_create_excel_file, name='agent_productivity_create_excel_file'),
    path('reports/agent_productivity/create_pdf_file', views.agent_productivity_create_pdf_file, name='agent_productivity_create_pdf_file'),

    path('reports/collector_goal_summary', views.collector_goal_summary, name='collector_goal_summary'),
    path('reports/collector_goal_summary/get_table_data', views.collector_goal_summary_get_table_data, name='collector_goal_summary_get_table_data'),

    path('reports/pay_for_performance', views.pay_for_performance, name='pay_for_performance'),
    path('reports/pay_for_performance/add_remove', views.pay_for_performance_add_remove, name='pay_for_performance_add_remove'),
    path('reports/pay_for_performance/delete/<str:employee_id>', views.pay_for_performance_delete, name='pay_for_performance_delete'),
    path('reports/pay_for_performance/get_table_data', views.pay_for_performance_get_table_data, name='pay_for_performance_get_table_data'),

    path('tools', views.tools, name='tools'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

riskmanagement/urls.py
from django.urls import path
from . import views

app_name = 'riskmanagement'

urlpatterns = [
    path('overview', views.overview, name='overview'),
    path('create_audit', views.create_or_edit_audit, name='create_audit'),
    path('edit_audit/<int:audit_id>', views.create_or_edit_audit, name='edit_audit'),
    path('delete_audit/<int:audit_id>', views.delete_audit, name='delete_audit'),

    path('calls_per_week', views.calls_per_week_audit, name='calls_per_week_audit'),
    path('state_dialing', views.state_dialing_audit, name='calls_per_week_audit'),

    path('api/audits', views.audit_list_view.as_view(), name='audit-list'),
]

mab/models.py
from django.db import models
from django.contrib.auth.models import User

class DashboardLink(models.Model):
    DEPARTMENT_CHOICES = [
        (1, 'Client Relations'),
        (2, 'Collections'),
        (3, 'Customer Service'),
        (4, 'Human Resources'),
        (5, 'Information Technology'),
        (6, 'Operations'),
        (7, 'Postng'),
        (8, 'Quality Assurance'),
        (9, 'Training'),
        (10, 'Risk Management'),
    ]

    TOOL_TYPE_CHOICES = [
        (1, 'Tool'),
        (2, 'Report'),
    ]

    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    department = models.IntegerField(choices=DEPARTMENT_CHOICES)
    type = models.IntegerField(choices=TOOL_TYPE_CHOICES)

    def get_department_disply(self):
        return dict(self.DEPARTMENT_CHOICES).get(self.department, '')
    
    def get_type_display(self):
        return dict(self.TOOL_TYPE_CHOICES).get(self.type, '')


class UserDashboard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    link = models.ForeignKey(DashboardLink, on_delete=models.CASCADE)

class Notifications(models.Model):
    NOTIFICATION_PRIORITY_CHOICES = [
        (1, 'High'),
        (2, 'Medium'),
        (3, 'Low'),
    ]

    NOTIFICATION_ACTION_CHOICES = [
        (1, 'View'),  # simply view notification
        (2, 'Reply'),  # request reply
        (3, 'Notify'),  # notify when read
        (4, 'Review'),  # accept or reject
    ]

    recipient = models.ForeignKey(User, related_name='received_notifications', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='sent_notifications', on_delete=models.CASCADE, null=True, blank=True)
    action = models.IntegerField(choices=NOTIFICATION_ACTION_CHOICES)
    priority = models.IntegerField(choices=NOTIFICATION_PRIORITY_CHOICES)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)
    is_read = models.BooleanField(default=False)
    link = models.CharField(max_length=255)

mab/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import DashboardLink, UserDashboard

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('dashboard'))
        else:
            return render(request, 'mab/login.html', {'error_message': 'Invalid credentials'})
    else:
        if request.user.is_authenticated:
            return redirect('dashboard')
        else:
            return render(request, 'mab/login.html')
    

@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


@login_required
def dashboard(request):
    links_in_dashboard = UserDashboard.objects.filter(user=request.user).select_related('link').order_by('link__name')
    return render(request, 'mab/dashboard.html', {'links_in_dashboard': links_in_dashboard})


@login_required
def add_tool_to_dashboard(request, link_name):
    user = request.user
    link = DashboardLink.objects.get(name=link_name)

    if not UserDashboard.objects.filter(user=user, link=link).exists():
        UserDashboard.objects.create(user=user, link=link)
        messages.success(request, f"{link.name} has been added to your dashboard")

    referring_url = request.META.get('HTTP_REFERER')
    if referring_url:
        return redirect(referring_url)
    else:
        return redirect('dashboard')


@login_required
def remove_tool_from_dashboard(request, link_name):
    link = DashboardLink.objects.get(name=link_name)
    user_dashboard_entry = get_object_or_404(UserDashboard, user=request.user, link=link)

    user_dashboard_entry.delete()
    messages.success(request, f"{link.name} has been removed from your dashboard")

    referring_url = request.META.get('HTTP_REFERER')
    if referring_url:
        return redirect(referring_url)
    else:
        return redirect('dashboard')

mab/templates/mab/base.html
{% load static %}
{% load bootstrap4 %}
<html>
    <head>
        <title>MAB KPI Web</title>
        <link rel="stylesheet" href="{% static 'mab/bootstrap/css/bootstrap.min.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
              rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=mail" />

        {% block head %}
        {% endblock head %}
    </head>

    <body style="background-color: #FFFFFF; margin-bottom: 20px;">
        <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #0251A7;">
            <div class="container-fluid">

                <a class="navbar-brand" href="#">
                    <img src="{% static 'mab/images/logo.gif' %}" alt="Logo" style="border: 3px solid white;">
                </a>

                {% if user.is_authenticated %}
                    <ul class="navbar-nav">

                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                        </li>
                        {% if perms.clientrelations.access_client_relations %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clientrelations:general_tools' %}">Client Relations</a>
                        </li>
                        {% endif %}
                        {% if perms.operations.access_operations %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'operations:reports' %}">Operations</a>
                        </li>
                        {% endif %}
                        {% if perms.riskmanagement.access_risk_management %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'riskmanagement:overview' %}">Risk Management</a>
                        </li>
                        {% endif %}
                    </ul>
                    <div class="ml-auto">
                        <a href="{% url 'logout' %}" class="btn btn-primary">logout</a>
                    </div>
                {% else %}
                    <div class="ml-auto">
                        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
                    </div>
                {% endif %}
                
            </div>
        </nav>

        <div class="container pt-3">
            {% block content %}
            {% endblock content %}
        <div>

        <script src="{% static 'mab/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        {% block scripts %}

        {% endblock %}
    </body> 
</html>

mab/templates/mab/dashboard.html
{% extends 'mab/base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-12">

            {% if messages %}
                <ul style="list-style-type: none">
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success">
                                <li>{{ message }}</li>
                            </div>
                        {% elif message.tags == 'info' %}
                            <div class="alert alert-info">
                                <li>{{ message }}</li>
                            </div>
                        {% elif message.tags == 'warning' %}
                            <div class="alert alert-warning">
                                <li>{{ message }}</li>
                            </div>
                        {% elif message.tags == 'error' %}
                            <div class="alert alert-danger">
                                <li>{{ message }}</li>
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}

            {% if links_in_dashboard %} 

            <div class="col-12 text-center">
                <h1 class="mx-auto">Dashboard</h1>
            </div>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entry in links_in_dashboard %}
                        <tr>
                            <td><a href="{{ entry.link.link }}">{{ entry.link.name }}</a></td>
                            <td>{{ entry.link.description }}</td>
                            <td>
                                <a href="{% url 'remove_tool_from_dashboard' entry.link.name %}" style="color: black;  ">
                                <span class="material-icons" title="Remove from Dashboard">remove_circle</span>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}   
            <div class="row">
                <div class="col-12 text-center">
                    <h3 class="mx-auto">You have not added anything to your dashboard.</h3>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

mab/templates/mab/login.html
{% extends 'mab/base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% comment %} <h1>Log In</h1> {% endcomment %}
            {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username"  autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter your username"  autocomplete="off">
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 5px;">Log In</button>    
            </form>
        </div>
    </div>
</div>
{% endblock content %}

mab/templates/mab/tool_add_remove_buttons.html
{% if user.is_authenticated %}
    {% if link_name in links_in_dashboard %}
        <a class="btn btn-light" style="position: fixed; bottom: 10px; right: 10px;"
            href="{% url 'remove_tool_from_dashboard' link_name %}"
            title="Remove from Dashboard"><span class="material-icons">remove_circle</span></a>
    {% else %}
        <a class="btn btn-light" style="position: fixed; bottom: 10px; right: 10px;"
            href="{% url 'add_tool_to_dashboard' link_name %}"
            title="Add to Dashboard"><span class="material-icons">add_circle</span></a>
    {% endif %}
{% endif %}