mab/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('add_tool/<str:link_name>', views.add_tool_to_dashboard, name='add_tool_to_dashboard'),
    path('remove_tool/<str:link_name>', views.remove_tool_from_dashboard, name='remove_tool_from_dashboard'),
    path('admin', admin.site.urls),
    path('clientrelations/', include('clientrelations.urls', namespace='clientrelations')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('riskmanagement/', include('riskmanagement.urls', namespace='riskmanagement')),
    path('', RedirectView.as_view(url=reverse_lazy('login'), permanent=True)),
]

riskmanagement/urls.py
from django.urls import path
from . import views

app_name = 'riskmanagement'

urlpatterns = [
    path('overview', views.overview, name='overview'),
    path('create_audit', views.create_or_edit_audit, name='create_audit'),
    path('edit_audit/<int:audit_id>', views.create_or_edit_audit, name='edit_audit'),
    path('delete_audit/<int:audit_id>', views.delete_audit, name='delete_audit'),

    path('calls_per_week', views.calls_per_week_audit, name='calls_per_week_audit'),
    path('state_dialing', views.state_dialing_audit, name='calls_per_week_audit'),

    path('api/audits', views.audit_list_view.as_view(), name='audit-list'),
]

riskmanagement/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class RiskManagementPermissions(models.Model):
    """
    Dummy model for defining custom permission related to Client Relations.
    """

    class Meta:
        managed = False  # don't create the model in the database
        permissions = [
            ("access_risk_management", "Can access the Risk Management section"),
        ]


class AuditType(models.Model):
    AUDIT_TYPE_DEPARTMENT_CHOICES = [
        ('posting', 'Posting'),
        ('performance', 'Performance'),
        ('information technology', 'Information Technology '),
        ('human resources', 'Human Resources'),
        ('compliance', 'Compliance'),
        ('collections', 'Collections'),
        ('accounting', 'Accounting'),
    ]

    AUDIT_TYPE_FREQUENCY_CHOICES = [
        (1, 'Daily'),  # key cooresponds to frequency of audits
        (7, 'Weekly'),
        (14, 'Bi-Weekly'),
        (30, 'Monthly'),
        (60, 'Bi-Monthly'),
        (90, 'Quartlery'),
        (180, 'Bi-Annually'),
        (356, 'Annually'),
    ]

    AUDIT_TYPE_RISK_LEVEL_CHOICES = [
        (2, 'High'),  # key cooresponds to the number of days a response is need in
        (3, 'Medium'),
        (5, 'Low'),
    ]
    
    department = models.CharField(choices=AUDIT_TYPE_DEPARTMENT_CHOICES)  # area of business the audit is focused on 
    name = models.CharField(max_length=255)  # name of the audit
    risk_level = models.IntegerField(choices=AUDIT_TYPE_RISK_LEVEL_CHOICES)  # the level of impact issues have on the company and clients
    testing_frequency = models.IntegerField(choices=AUDIT_TYPE_FREQUENCY_CHOICES)  # how often the audit is performed
    passing_score = models.IntegerField()  # not sure if this is actually needed

    def __str__(self):
        return self.name


class Audit(models.Model):
    AUDIT_CLIENT_CHOICES = [
        (0, 'Business'),  
        (1, "Collections"),
        (2, 'REM'),  
        (3, 'AnotherBank'),
        (4, 'AClient'),
        (5, 'InsuranceComp'),
        (6, 'Bank'),
        (7, 'AStore'),
        (8, 'Finance'),
        (9, 'Clothes'),
        (10, 'The Bank'),
    ]

    audit_type = models.ForeignKey(AuditType, on_delete=models.CASCADE)  # the audit that was conducted
    auditor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)  # the person performing the audit
    client = models.IntegerField(choices=AUDIT_CLIENT_CHOICES, default=0)  # client associated with the audit
    start_date = models.DateField()  # date when audit becomes available to run
    due_date = models.DateField()  # the date the audit needs to be done by
    date_ran = models.DateField(null=True)  # date the audit was run
    created_at = models.DateTimeField(auto_now_add=True)  # date audit was created
    eval_start_date = models.DateField(null=True)  # the begining of the period that was aduited
    eval_end_date =  models.DateField(null=True)  # the end of the period audited 

    def next_audit_date(self):
        return self.due_date + timezone.timedelta(days=self.audit_type.testing_frequency)


class AuditFinding(models.Model):
    AUDIT_STATUS_CHOICES = [
        (1, 'Open'),
        (2, 'Closed'),
        (3, 'In Progress'),
    ]

    audit = models.ForeignKey(Audit, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    date_identified = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=AUDIT_STATUS_CHOICES)
    assigned_to = models.ForeignKey(User, on_delete=models.PROTECT)
    description = models.TextField()
    recommendations = models.TextField()
    actions_taken = models.TextField()
    documentation = models.FileField(upload_to='audit_documents', null=True, blank=True)  # Need to actually set up a location to store these

    def remediation_due_date(self):
        return self.date_identified + timezone.timedelta(days=self.audit.audit_type.risk_level)


class StateDialingAudit(models.Model):
    audit = models.OneToOneField(Audit, on_delete=models.CASCADE)
    calls_evaluated = models.IntegerField(null=True)  
    unique_calls_evaluated = models.IntegerField(null=True)
    fdcpa_early	= models.IntegerField(null=True)
    fdcpa_Late = models.IntegerField(null=True)
    michigan_early = models.IntegerField(null=True)	
    oklahoma_early = models.IntegerField(null=True)	
    oregon_early = models.IntegerField(null=True)
    texas_early	= models.IntegerField(null=True)
    texas_sunday = models.IntegerField(null=True)

    def total_defective(self):
        total = self.fdcpa_early + self.fdcpa_Late + self.michigan_early + self.oklahoma_early + self.oregon_early + self.texas_early + self.texas_sunday
        return(total)


class CallsPerWeekAudit(models.Model):
    audit = models.OneToOneField(Audit, on_delete=models.CASCADE)
    calls_evaluated = models.IntegerField(null=True)  
    unique_calls_evaluated = models.IntegerField(null=True) 


class CallsPerWeekExtraCalls:
    calls_per_week_audit = models.OneToOneField(CallsPerWeekAudit, on_delete=models.CASCADE)  # audit it is associated with
    cubs_account_number = models.IntegerField()  # the account that was called
    num_of_calls = models.IntegerField()  # number of calls made in time period


class CallsPerWeekReview(models.Model):
    calls_per_week_audit = models.OneToOneField(CallsPerWeekAudit, on_delete=models.CASCADE)  # audit it is associated with
    cubs_account_number = models.IntegerField()	# the account that was called
    call_date = models.DateTimeField()  # the begining of the time period where contatct was made
    end_date = models.DateTimeField()  # the date it would have been okay to call again
    contact_tally = models.IntegerField()  # number of calls made in that period
    notes = models.TextField(null=True)  # evidence that the call was okay or not okay

riskmanagement/forms.py
from django import forms 
from .models import Audit


class AuditForm(forms.ModelForm):
    class Meta:
        model = Audit
        fields = ['audit_type', 'client', 'start_date', 'due_date',]

        widgets = {
            'due_date': forms.DateInput(attrs={'type': 'date'}),
            'start_date': forms.DateInput(attrs={'type': 'date'}),
        }

riskmanagement/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.db.models import Case, When, Value, CharField
from .models import Audit, StateDialingAudit, CallsPerWeekAudit
from .forms import AuditForm

from datetime import datetime
import subprocess
import json

from rest_framework import generics
from .serializers import AuditSerializer
# from mab.utils.pagination import CustomPagination


@login_required
@permission_required('riskmanagement.access_risk_management', raise_exception=True)
def overview(request):
    incomplete_aduits = Audit.objects.filter(date_ran__isnull=True).order_by('due_date')
    current_time = timezone.now().date()

    overview_context = {
        'audits': incomplete_aduits,
        'now': current_time,
    }

    return render(request, 'riskmanagement/riskmanagement_overview.html', overview_context)


@login_required
@permission_required('riskmanagement.access_risk_management', raise_exception=True)
def calls_per_week_audit(request):
    if request.method == 'POST':
        selected_audit_ids = request.POST.getlist('selected_audits')
        audits_to_run = Audit.objects.filter(id__in=selected_audit_ids, date_ran__isnull=True)
        
        print(selected_audit_ids)

        python_executable_path = "/mnt/python/python.exe"
        script_path = ""

        sql_query = "SELECT * FROM Employee"
        table = "Employee"

        result = subprocess.run([python_executable_path, script_path, sql_query, table], capture_output=True, text=True)

        if result.stderr:
            print(result.stderr)

        # data = json.loads(result.stdout)

        print(result.stdout)

        # return JsonResponse(data, safe=False)

    available_audits = Audit.objects.filter(audit_type__name='Calls Per Week', date_ran__isnull=True)

    return render(request, 'riskmanagement/calls_per_week.html', {'available_audits': available_audits})


@login_required
@permission_required('riskmanagement.access_risk_management', raise_exception=True)
def state_dialing_audit(request):
    return render(request, 'riskmanagement/state_dialing.html')


@login_required
@permission_required('riskmanagement.access_risk_management', raise_exception=True)
def create_or_edit_audit(request, audit_id=None):
    if audit_id:
        audit_instance = get_object_or_404(Audit, id=audit_id)
        audit_form = AuditForm(request.POST or None, instance=audit_instance)
        editing = True
    else:
        audit_instance = None
        audit_form = AuditForm(request.POST or None)
        editing = False

    if request.method == 'POST':
        
        if audit_form.is_valid():
            audit_instance = audit_form.save()

            submitted_audit_type = audit_instance.audit_type.name

            if str(submitted_audit_type) == 'State Dialing':
                specific_aduit, created = StateDialingAudit.objects.get_or_create(audit=audit_instance)
            elif str(submitted_audit_type) == 'Calls Per Week':
                specific_aduit, created = CallsPerWeekAudit.objects.get_or_create(audit=audit_instance)
            else:
                # SOMETHING BROKE!
                return HttpResponse("Invalid audit type")
            specific_aduit.save()

            messages.success(request, f'{str(submitted_audit_type)} Audit was successfully created.')
            return redirect('riskmanagement:overview')
            
    create_or_edit_context = {
        'audit_form': audit_form,
        'editing': editing,
    }
    return render(request, 'riskmanagement/create_or_edit_audit.html', create_or_edit_context)


@login_required
@permission_required('riskmanagement.access_risk_management', raise_exception=True)
def delete_audit(request, audit_id):
    audit = get_object_or_404(Audit, pk=audit_id)
    audit.delete()

    messages.success(request, f'{audit.audit_type.name}  Audit was successfully deleted.')
    return redirect('riskmanagement:overview')


class audit_list_view(generics.ListAPIView):
    today = datetime.today()

    queryset = Audit.objects.annotate(
        position=Case(
            When(due_date__lt=today, then=Value('0')),
            When(start_date__gt=today, then=Value('2')),
            default=Value('1'),
            output_field=CharField(),
        )
    )
    queryset = queryset.filter(date_ran__isnull=True).order_by('position')


    # queryset = Audit.objects.filter(date_ran__isnull=True).order_by('start_date', 'due_date')
    serializer_class = AuditSerializer
    # pagination_class = CustomPagination
    

riskmanagement/templates/riskmanagement/calls_per_week.html
{% extends 'mab/base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="col-12 text-center">
    <h1 class="mx-auto">Calls Per Week Audit</h1>
</div>

<div class="container mt-3">
    {% if messages %}
        <ul style="list-style-type: none">
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'info' %}
                    <div class="alert alert-info">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'warning' %}
                    <div class="alert alert-warning">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}


    <div class="container">
        <div class="row justify-content-center">
            <div class="col-auto" style="background-color: #F2F2F2">

                <form method="post">
                    {% csrf_token %}
                    <br>
                    {% for audit in available_audits %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="selected_audits" value="{{ audit.id }}" checked>
                            <label class="form-check-label" for="flexCheckDefault">
                                {{ audit.get_client_display }}
                            </label>
                        </div>
                    {% endfor %}
                    <br>
                    <button type="submit" class="btn btn-primary">Run Selected Audits</button>
                </form> 
                
            </div>
        </div>
    </div>

</div>

{% endblock content %}

riskmanagement/templates/riskmanagement/create_or_edit_audit.html
{% extends 'mab/base.html' %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block content %}

<div class="col-12 text-center">
    {% if editing %}
        <h1 class="mx-auto">Edit Audit</h1>
    {% else %}
        <h1 class="mx-auto">Create New Audit</h1>
    {% endif %}
</div>

<div class="container mt-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6" style="background-color: #F2F2F2">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3 mt-3">
                        <label for="{{ audit_form.audit_type.id }}" class="form-label">Audit Type:</label>
                        {{ audit_form.audit_type | add_class:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ audit_form.client.id }}" class="form-label">Client:</label>
                        {{ audit_form.client | add_class:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ audit_form.start_date.id }}" class="form-label">Start Date:</label>
                        {{ audit_form.start_date | add_class:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ audit_form.due_date.id }}" class="form-label">Due Date:</label>
                        {{ audit_form.due_date | add_class:"form-control" }}
                    </div>
                    <button type="sumbit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

riskmanagement/templates/riskmanagement/riskmanagement_overview.html
{% extends 'mab/base.html' %}
{% load bootstrap4 %}
{% load render_bundle from webpack_loader %}

{% block content %}

<div class="col-12 text-center">
    <h1 class="mx-auto">Risk Management</h1>
</div>

<div class="container mt-3">
    {% if messages %}
        <ul style="list-style-type: none">
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'info' %}
                    <div class="alert alert-info">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'warning' %}
                    <div class="alert alert-warning">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

    <a href="{% url 'riskmanagement:create_audit' %}" class="btn btn-light">Add Audit</a>

</div>

{% endblock content %}

riskmanagement/templates/riskmanagement/state_dialing.html
{% extends 'mab/base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="col-12 text-center">
    <h1 class="mx-auto">State Dialing Audit</h1>
</div>

<div class="container mt-3">
    {% if messages %}
        <ul style="list-style-type: none">
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'info' %}
                    <div class="alert alert-info">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'warning' %}
                    <div class="alert alert-warning">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">
                        <li>{{ message|linebreaksbr }}</li>
                    </div>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

    
</div>

{% endblock content %}