mab/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('add_tool/<str:link_name>', views.add_tool_to_dashboard, name='add_tool_to_dashboard'),
    path('remove_tool/<str:link_name>', views.remove_tool_from_dashboard, name='remove_tool_from_dashboard'),
    path('admin', admin.site.urls),
    path('clientrelations/', include('clientrelations.urls', namespace='clientrelations')),
    path('operations/', include('operations.urls', namespace='operations')),
    path('riskmanagement/', include('riskmanagement.urls', namespace='riskmanagement')),
    path('', RedirectView.as_view(url=reverse_lazy('login'), permanent=True)),
]

operations/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'operations'

urlpatterns = [
    path('reports', views.reports, name='reports'),

    path('reports/agent_productivity', views.agent_productivity, name='agent_productivity'),
    path('reports/agent_productivity/get_table_data', views.agent_productivity_get_table_data, name='agent_productivity_get_table_data'),
    path('reports/agent_productivity/create_excel_file', views.agent_productivity_create_excel_file, name='agent_productivity_create_excel_file'),
    path('reports/agent_productivity/create_pdf_file', views.agent_productivity_create_pdf_file, name='agent_productivity_create_pdf_file'),

    path('reports/collector_goal_summary', views.collector_goal_summary, name='collector_goal_summary'),
    path('reports/collector_goal_summary/get_table_data', views.collector_goal_summary_get_table_data, name='collector_goal_summary_get_table_data'),

    path('reports/pay_for_performance', views.pay_for_performance, name='pay_for_performance'),
    path('reports/pay_for_performance/add_remove', views.pay_for_performance_add_remove, name='pay_for_performance_add_remove'),
    path('reports/pay_for_performance/delete/<str:employee_id>', views.pay_for_performance_delete, name='pay_for_performance_delete'),
    path('reports/pay_for_performance/get_table_data', views.pay_for_performance_get_table_data, name='pay_for_performance_get_table_data'),

    path('tools', views.tools, name='tools'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/models.py
from django.db import models
import os


class OperationsPermissions(models.Model):
    """
    Dummy model for defining custom permission related to Client Relations.
    """

    class Meta:
        managed = False  # don't create the model in the database
        permissions = [
            ("access_operations", "Can access the Operations section"),
        ]
        


# Create your models here.
class PayForPerformance(models.Model):
    file_title = models.CharField(max_length=255)
    uploaded_file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        if self.uploaded_file:
            if os.path.isfile(self.uploaded_file.path):
                os.remove(self.uploaded_file.path)
        super(PayForPerformance, self).delete(*args, **kwargs)

    def __str__(self):
        return self.file_title


class PayForPerformanceEmployee(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    last_name_and_suffix = models.CharField()
    first_name = models.CharField()
    most_recent_hire_date = models.DateField(null=True, blank=True)
    supervisor = models.CharField(null=True, blank=True)
    pay_rate = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=20, choices=[('added', 'Added'), ('removed', 'Removed')])
    is_removed = models.BooleanField(default=False)


class AgentProductivity(models.Model):
    productvity_file_title = models.CharField(max_length=255)
    productivity_uploaded_file = models.FileField(upload_to='uploads/')
    calls_file_title = models.CharField(max_length=255)
    calls_uploaded_file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        if self.productivity_uploaded_file:
            if os.path.isfile(self.productivity_uploaded_file.path):
                os.remove(self.productivity_uploaded_file.path)
        if self.calls_uploaded_file:
            if os.path.isfile(self.calls_uploaded_file.path):
                os.remove(self.calls_uploaded_file.path)
        super(AgentProductivity, self).delete(*args, **kwargs)

operations/forms.py
from django import forms
from .models import AgentProductivity

class EmployeeForm(forms.Form):
    ACTION_CHOICES = [
        ('add', 'Add'),
        ('remove', 'Remove'),
    ]

    id = forms.IntegerField(label="Employee ID", required=True, widget=forms.NumberInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Employee ID',
        }
    ))

    last_name_and_suffix = forms.CharField(label="Employee Last Name and Suffix", max_length=35, required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Employee Last Name and Suffix',
        }
    ))

    first_name = forms.CharField(label="Employee First Name", max_length=25, required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Employee First Name',
        }
    ))

    most_recent_hire_date = forms.DateField(label="Most Recent Hire Date", required=False, widget=forms.DateInput(
        attrs={
            'type': 'date',
            'class': 'form-control',
        }
    ))

    supervisor = forms.CharField(label="Supervisor", max_length=60, required=False,  widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Supervisor Name',
        }
    ))

    pay_rate = forms.DecimalField(label="Pay Rate", required=False,  widget=forms.NumberInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Pay Rate',
        }
    ))

    action = forms.ChoiceField(choices=ACTION_CHOICES, widget=forms.RadioSelect, initial='add', required=True, )


class AgentProductivityForm(forms.ModelForm):
    class Meta:
        model = AgentProductivity
        fields = ['productivity_uploaded_file', 'calls_uploaded_file']

class AgentProductivityForm(forms.Form):
    productivity_file = forms.FileField(label="Agent Productivity Log", required=True, widget=forms.FileInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Upload Agent Productivity File',
        }
    ))

    calls_file = forms.FileField(label="Agent Call Log", required=True, widget=forms.FileInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Upload Agent Call Log File',
        }
    ))

operations/views.py
import pandas as pd
import json
import requests
import os
from weasyprint import HTML
from datetime import datetime, timedelta, timezone
from dateutil.relativedelta import relativedelta
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.template.loader import render_to_string
from urllib.parse import urlencode
from .models import PayForPerformance, PayForPerformanceEmployee, AgentProductivity
from .forms import EmployeeForm, AgentProductivityForm
from .utils import create_pfp_spreadsheet, create_pfp_dataframe, pay_for_performance_query_transactions, agent_productivity_process_data

from io import BytesIO
import openpyxl
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side, NamedStyle

# Create your views here.
@login_required
@permission_required('operations.access_operations', raise_exception=True)
def reports(request):
    return render(request, 'operations/reports.html')


@login_required
@permission_required('operations.access_operations', raise_exception=True)
def tools(request):
    return render(request, 'operations/tools.html')


@login_required
@permission_required('operations.access_operations', raise_exception=True)
def pay_for_performance(request):
    # Upload file from paychex
    if request.method == 'POST' and request.FILES.get('file'):
        uploaded_file = request.FILES['file']

        # Make sure the file is an excel spreadsheet
        if not uploaded_file.name.endswith(('.xlsx', '.xls')):
            messages.error(request, 'The uploaded file was not an excel spreadsheet')
        else:
            required_columns = ['Employee ID', 'Employee Last Name and Suffix', 'Employee First Name', 'Most Recent Hire Date', 'Supervisor', 'Pay Rate 1',]
            df = pd.read_excel(uploaded_file) 
            missing_columns = [col for col in required_columns if col not in df.columns]

            # Make sure the spreadsheet has the required columns
            if missing_columns:
                messages.error(request, f'The uploaded spreadsheet is missing required columns: {', '.join(missing_columns)}')
            else:
                # Iterate through because a bulk delete will not trigger overridden delete function
                for instance in PayForPerformance.objects.all():
                    instance.delete()
                #PayForPerformance.objects.all().delete()

                file_instance = PayForPerformance(uploaded_file=uploaded_file, file_title=uploaded_file.name)
                file_instance.save()

                messages.success(request, 'File uploaded successfully.')

    context = {}

    file_instance = PayForPerformance.objects.last()

    # Add file information to context if their is one on file
    if file_instance:
        context["file_name"] = file_instance.file_title
        context["uploaded_date"] = file_instance.uploaded_at

    # Calucalte the start and end dates for the report
    endDate = datetime.today() - relativedelta(months=1)
    year = endDate.year
    month = endDate.month
    end_month = endDate.strftime('%Y-%m')

    # Override the year and month with values from dateInput in form if it exists in request
    if request.method == 'POST' and file_instance:
        year, month = request.POST.get('dateInput', end_month).split('-')

    end_date = datetime(int(year), int(month), 1) + timedelta(days=32)
    end_date = end_date.replace(day=1) - timedelta(days=1)

    start_date = datetime(int(year), int(month), 1) - relativedelta(months=5)

    # Convert datetime objects to strings to use in query
    startDate = start_date.strftime('%Y-%m-%d')
    endDate = end_date.strftime('%Y-%m-%d')

    # Create excel file
    if request.method == 'POST' and request.POST.get('create_pfp_excel_file'):
        file_path = file_instance.uploaded_file.path

        df = pd.read_excel(file_path)

        combined_df, transaction_data = pay_for_performance_query_transactions(df, startDate, endDate)

        final_data = create_pfp_dataframe(combined_df, transaction_data)

        pfp_spreadsheet_buffer = create_pfp_spreadsheet(final_data)

        response = HttpResponse(pfp_spreadsheet_buffer, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename="pfp.xlsx"'

        return response

    context["selected_date"] = endDate.rsplit('-', 1)[0]    

    return render(request, 'operations/pay_for_performance.html', context)


@login_required
@permission_required('operations.access_operations', raise_exception=True)
def pay_for_performance_get_table_data(request):
    file_instance = PayForPerformance.objects.last()

    if not file_instance:
        return JsonResponse({}, content_type="application/json", status=204)
        return None
    
    # Calculate the required start and end months for report
    endDate = datetime.today() - relativedelta(months=1)
    year = endDate.year
    month = endDate.month
    end_month = endDate.strftime('%Y-%m')

    if request.method == 'POST' and file_instance:
        date_post_data = json.loads(request.body)
        dateInput = date_post_data['dateInput']

        if dateInput:
            year, month = str(dateInput).split('-')
        else:
            year, month = end_month.split('-')

    end_date = datetime(int(year), int(month), 1) + timedelta(days=32)
    end_date = end_date.replace(day=1) - timedelta(days=1)

    start_date = datetime(int(year), int(month), 1) - relativedelta(months=5)

    startDate = start_date.strftime('%Y-%m-%d')
    endDate = end_date.strftime('%Y-%m-%d')

    file_path = file_instance.uploaded_file.path

    df = pd.read_excel(file_path)

    combined_df, transaction_data = pay_for_performance_query_transactions(df, startDate, endDate)

    final_data = create_pfp_dataframe(combined_df, transaction_data)
    
    final_data_dict = final_data.to_dict(orient='records')

    return JsonResponse(final_data_dict, safe=False)


@login_required
@permission_required('operations.access_operations', raise_exception=True)
def pay_for_performance_add_remove(request):
    # Retrieve added and removed employees
    added_employees = PayForPerformanceEmployee.objects.filter(status='added', is_removed=False).order_by('first_name')
    removed_employees = PayForPerformanceEmployee.objects.filter(status='removed', is_removed=False).order_by('first_name')

    if request.method == 'POST':
        form = EmployeeForm(request.POST)

        if form.is_valid():
            action = form.cleaned_data['action']

            if action == 'add':
                employee = PayForPerformanceEmployee(
                    id=form.cleaned_data['id'],
                    last_name_and_suffix=form.cleaned_data['last_name_and_suffix'],
                    first_name=form.cleaned_data['first_name'],
                    most_recent_hire_date=form.cleaned_data['most_recent_hire_date'],
                    supervisor=form.cleaned_data['supervisor'],
                    pay_rate=form.cleaned_data['pay_rate'],
                    status='added',
                    is_removed=False,
                )

                employee.save()

                redirect('operations:pay_for_performance_add_remove')

            if action == 'remove':
                employee = PayForPerformanceEmployee(
                    id=form.cleaned_data['id'],
                    last_name_and_suffix=form.cleaned_data['last_name_and_suffix'],
                    first_name=form.cleaned_data['first_name'],
                    status='removed',
                    is_removed=False,
                )

                employee.save()

                redirect('operations:pay_for_performance_add_remove')
    
    form = EmployeeForm()

    context = {
        'form': form,
        'added_employees': added_employees,
        'removed_employees': removed_employees,
    }

    return render(request, 'operations/pay_for_performance_add_remove.html', context)


@login_required
@permission_required('operations.access_operations', raise_exception=True)
def pay_for_performance_delete(request, employee_id):
    employee = get_object_or_404(PayForPerformanceEmployee, id=employee_id)
    employee.is_removed = True
    employee.save()
    
    return redirect('operations:pay_for_performance_add_remove')


@login_required
@permission_required('operations.access_operations', raise_exception=True)
def agent_productivity(request):
    if request.method == 'POST':
        form = AgentProductivityForm(request.POST, request.FILES)

        if form.is_valid():
            
            productivity_file = form.cleaned_data['productivity_file']
            calls_file = form.cleaned_data['calls_file']

            if not productivity_file.name.endswith(('.xlsx', '.xls')):
                messages.error(request, 'The uploaded Agent Productivity Log is not an excel spreadsheet')
            if not calls_file.name.endswith(('.xlsx', '.xls')):
                messages.error(request, 'The uploaded Agent Call Log is not an excel spreadsheet')
            if productivity_file.name.endswith(('.xlsx', '.xls')) and calls_file.name.endswith(('.xlsx', '.xls')):
                productivity_required_columns = ['Agent', 'Total Calls', 'Inbound Calls', 'Transfers', 'Mobile Comply', 'PD', 'Outbound Manual Calls', 'In Call (Min)', 
                                                 'In Call (%)', 'Ready', 'Ready (%)', 'Wrapup', 'Wrapup (%)', 'Not Ready', 'Not Ready (%)', 'Total Login Time', 'Total RPC', 
                                                 'Total WPC', 'Non-Contacts',]
                productivity_df = pd.read_excel(productivity_file, skiprows=2) 

operations/templates/operations/agent_productivity.html
{% extends 'operations/op_base_templates/op_report_base.html' %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block report_content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="mx-auto">Agent Productivity Report</h1>
        </div>
    </div>

    {% if last_upload %}
        <p>Files last uploaded on {{ last_upload }}</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

    <div class="container mt-2 mb-2">
        <a class="btn btn-secondary me-2" href="{% url 'operations:agent_productivity_create_excel_file' %}" >Create Excel File</button>
        <a class="btn btn-secondary me-2" href="{% url 'operations:agent_productivity_create_pdf_file' %}" style="float:right">Create PDF File</a>
    </div>

    <div id="app">
        <div v-if="json_is_blank" class="pb-2">
            <h3 class="text-center">Upload a Dial Connection files to create a report</h3>
        </div>

        <div v-else-if="loading" class="pb-2">
            <h3 class="text-center">Loading...</h3>
        </div>

        <div v-else>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th v-for="(value, key) in data[0]" :key="key">[[ key ]]</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(row, index) in data" :key="index">
                            <td v-for="(value, key) in row" :key="key">[[ formatValue(value, key) ]]</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock report_content %}

{% block add_remove_button %}
    {% include 'mab/tool_add_remove_buttons.html' with link_name='Agent Productivity Report' %}
{% endblock add_remove_button %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

<script>
    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            loading: true,
            json_is_blank: false,
            data: [],
        },
        mounted() {
            fetch('{% url 'operations:agent_productivity_get_table_data' %}')
                .then(response => response.json())
                .then(json => {
                    this.data = json;
                    this.loading = false;
                })
                .catch(error => {
                    this.json_is_blank = true;
                    console.error('Error parsing JSON: ', error);
                });
        },
        methods: {
            formatValue(value, key) {
                // Specify which keys should be formatted as percentages
                percentageColumns = ['In Call (%)', 'Ready (%)', 'Wrapup (%)', 'Not Ready (%)', 'Conversion Rate',];

                if (percentageColumns.includes(key)) {
                    if (typeof value === 'number') {
                        // Round to two decimal places if it's a decimal
                        return (value * 100).toFixed(2) + '%';
                    } else {
                        return '-';
                    }
                }

                return value                
            },
        }
    });
</script>
{% endblock scripts %}

operations/templates/operations/collector_goal_summary.html
{% extends 'operations/op_base_templates/op_report_base.html' %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block report_content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="mx-auto">Collector Goal Summary Report</h1>
        </div>
    </div>

    <div id="app">
        <form form @submit.prevent="get_collector_goal_summary_data" class="mt-3 mb-3">
            {% csrf_token %}
            <div class="form-group input-group form-row align-items-center">
                <label class="me-2" for="dateInput">Date</label>
                <input type="date" class="form-control" id="dateInput" name="dateInput" v-model="date_input" required>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </div>
        </form>

        <div v-if="loading" class="pb-3">
            <h3 class="text-center">Loading...</h3>
        </div>
        <div v-else>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th v-for="(value, key) in data[0]" :key="key">[[ key ]]</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(row, index) in data" :key="index">
                            <td v-for="(value, key) in row" :key="key">[[ formatValue(value) ]]</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
{% endblock report_content %}

{% block add_remove_button %}
    {% include 'mab/tool_add_remove_buttons.html' with link_name='Collector Goal Summary' %}
{% endblock add_remove_button %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

<script>
    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            loading: true,
            date_input: "{{ selected_date }}",
            data: [],
        },
        mounted() {
            fetch('{% url 'operations:collector_goal_summary_get_table_data' %}')
                .then(response => response.json())
                .then(json => {
                    this.data = json;
                    this.loading = false;
                })
                .catch(error => {
                    console.error('Error parsing JSON: ', error);
                });
        },
        methods: {
            formatValue(value) {
                // Check if value is a number
                if (typeof value === 'number') {
                    // Round to two decimal places if it's a decimal
                    return value % 1 !== 0 ? value.toFixed(2) : value;
                }

                return value;
            },
            get_collector_goal_summary_data() {
                this.loading = true;

                fetch('{% url 'operations:collector_goal_summary_get_table_data' %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    body: JSON.stringify({ dateInput: this.date_input }),
                })
                .then(response => response.json())
                .then(json => {
                    this.data = json;
                    this.loading = false;
                })
                .catch(error => {
                    console.error('Error parsing JSON: ', error);
                });
            }
        }
    });
</script>
{% endblock scripts %}

operations/templates/operations/pay_for_performance_add_remove.html
{% extends 'operations/op_base_templates/op_report_base.html' %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block report_content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="mx-auto">Pay for Performance Report</h1>
            <h2 class="mx-auto">Add/Remove Employees</h2>
        </div>
    </div>

    <div class="row">
    <div class="d-flex mb-2">
        <a href="{% url 'operations:pay_for_performance' %}" class="btn btn-secondary" style="float:right">Back to Report</a>
    </div>
    </div>

    <form method="POST" id="add_remove_form" autocomplete="off">
        {% csrf_token %}

        <div class="row">
            <div class="form-group col">
                {{ form.id.label_tag }}
                {{ form.id }}
            </div>
            <div class="form-group col">
                {{ form.last_name_and_suffix.label_tag }}
                {{ form.last_name_and_suffix }}
            </div>
            <div class="form-group col">
                {{ form.first_name.label_tag }}
                {{ form.first_name }}
            </div>
        </div>

        <div class="row">
            <div class="form-group col">
                {{ form.most_recent_hire_date.label_tag }}
                {{ form.most_recent_hire_date }}
            </div>
            <div class="form-group col">
                {{ form.supervisor.label_tag }}
                {{ form.supervisor }}
            </div>
            <div class="form-group col">
                {{ form.pay_rate.label_tag }}
                {{ form.pay_rate }}
            </div>
        </div>

        <div class="form-group">
            {{ form.action.label_tag }}
            {{ form.action }}
        </div>

        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>

    <h3>Added Employees</h3>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name and Suffix</th>
                <th>Supervisor</th>
                <th>Most Recent Hire Date</th>
                <th>Pay Rate</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for employee in added_employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name_and_suffix }}</td>
                <td>{{ employee.supervisor }}</td>
                <td>{{ employee.most_recent_hire_date }}</td>
                <td>{{ employee.pay_rate }}</td>
                <td>
                    <a href="{% url 'operations:pay_for_performance_delete' employee.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Removed Employees</h3>
    <table e class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name and Suffix</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for employee in removed_employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name_and_suffix }}</td>
                <td>
                    <a href="{% url 'operations:pay_for_performance_delete' employee.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock report_content %}

{% block scripts %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const actionRadio = document.getElementsByName('action');
        const supervisorNameField = document.getElementById('id_supervisor');
        const hireDateNameField = document.getElementById('id_most_recent_hire_date');
        const payRateNameField = document.getElementById('id_pay_rate');
        const form = document.getElementById('add_remove_form')

        function toggleRequired() {
            const selectedAction = document.querySelector('input[name="action"]:checked').value;

            if (selectedAction === 'add') {
                supervisorNameField.required = true;
                hireDateNameField.required = true;
                payRateNameField.required = true;
            } else {
                supervisorNameField.required = false;
                hireDateNameField.required = false;
                payRateNameField.required = false;
            } 
        }

        // Set initial state based on default radio button selection 
        toggleRequired();

        // Listen for changes on radio button
        actionRadio.forEach(radio => {
            radio.addEventListener('change', toggleRequired);
        });
    })
</script>
{% endblock scripts %}

operations/templates/operations/reports.html
{% extends 'operations/op_base_templates/op_base.html' %}
{% load bootstrap4 %}

{% block index_content %}
<div class="container">
    <div class="row">
        <h2 class="mt-3 text-center">Reports</h2>
        <div class="col-sm-4">
            <div class="list-group mt-3 mb-3">
                <a href="{% url 'operations:pay_for_performance' %}" class="list-group-item list-group-item-action">Pay for Peformance</a>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="list-group mt-3 mb-3">
                <a href="{% url 'operations:agent_productivity' %}" class="list-group-item list-group-item-action">Agent Productivity</a>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="list-group mt-3 mb-3">
                <a href="{% url 'operations:collector_goal_summary' %}" class="list-group-item list-group-item-action">Collector Goal Summary</a>
            </div>
        </div>
    </div>
</div>
{% endblock index_content %}

operations/templates/operations/tools.html
{% extends 'operations/op_base_templates/op_base.html' %}
{% load bootstrap4 %}

{% block index_content %}
<div class="container">
    <div class="row">
        <h2 class="mt-3 text-center">Tools</h2>
        {% comment %} <div class="col-sm-4">
            <div class="list-group mt-3 mb-3">
                <a href="{% url 'operations:letter_retrieval' %}" class="list-group-item list-group-item-action">Letter Search</a>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="list-group mt-3 mb-3">
                <a href="{% url 'operations:agent_productivity' %}" class="list-group-item list-group-item-action">Agent Productivity</a>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="list-group mt-3 mb-3">
                <a href="{% url 'operations:collector_goal_summary' %}" class="list-group-item list-group-item-action">Collector Goal Summary</a>
            </div>
        </div>  {% endcomment %}
    </div>
</div>
{% endblock index_content %}